// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdChdOd8djMXinVPkiTGvcTWc0AsKXIV8',
    appId: '1:1004929737963:web:ecaaaa0079076e2b62caae',
    messagingSenderId: '1004929737963',
    projectId: 'neuralens-7548c',
    authDomain: 'neuralens-7548c.firebaseapp.com',
    storageBucket: 'neuralens-7548c.firebasestorage.app',
    measurementId: 'G-F4HNS034PT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1aExVwDLNBWXtcvUpymmEuTgiG6r_81w',
    appId: '1:1004929737963:android:2b088a1acac48b1262caae',
    messagingSenderId: '1004929737963',
    projectId: 'neuralens-7548c',
    storageBucket: 'neuralens-7548c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZUmwaSRi8Z1JrZ5_AzC_wGnY42rfx9Ow',
    appId: '1:1004929737963:ios:f607ef57b53a70f062caae',
    messagingSenderId: '1004929737963',
    projectId: 'neuralens-7548c',
    storageBucket: 'neuralens-7548c.firebasestorage.app',
    iosBundleId: 'com.example.firstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZUmwaSRi8Z1JrZ5_AzC_wGnY42rfx9Ow',
    appId: '1:1004929737963:ios:f607ef57b53a70f062caae',
    messagingSenderId: '1004929737963',
    projectId: 'neuralens-7548c',
    storageBucket: 'neuralens-7548c.firebasestorage.app',
    iosBundleId: 'com.example.firstone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdChdOd8djMXinVPkiTGvcTWc0AsKXIV8',
    appId: '1:1004929737963:web:0c67d9e0e27d4a4a62caae',
    messagingSenderId: '1004929737963',
    projectId: 'neuralens-7548c',
    authDomain: 'neuralens-7548c.firebaseapp.com',
    storageBucket: 'neuralens-7548c.firebasestorage.app',
    measurementId: 'G-KS1J4WKMQZ',
  );

}